// Generated by CoffeeScript 1.6.2
(function() {
  var canvas, game;

  canvas = document.createElement('canvas');

  document.body.appendChild(canvas);

  window.game = game = 'game';

}).call(this);

/*
//@ sourceMappingURL=game.map
*/
