// Generated by CoffeeScript 1.6.3
(function() {
  describe('The game surface', function() {
    var surface;
    surface = null;
    beforeEach(function() {
      game.load();
      game.engine.init();
      return surface = game.engine.surface;
    });
    return it('should be 4000 x 3000', function() {
      expect(surface.width).toBe(4000);
      return expect(surface.height).toBe(3000);
    });
  });

}).call(this);
