// Generated by CoffeeScript 1.6.2
(function() {
  describe('The game', function() {
    it('should have a surface', function() {
      return expect(game.surface).toBeDefined();
    });
    it('can be initialized', function() {
      return expect(game.init).toBeDefined();
    });
    it('has a HUD', function() {
      return expect(game.hud).toBeDefined();
    });
    it('should be paused by default', function() {
      return expect(game.isPaused()).toBeTruthy();
    });
    it('can be updated', function() {
      return expect(typeof game.update).toBe('function');
    });
    describe('when paused', function() {
      beforeEach(function() {
        return game.pause();
      });
      return it('can be resumed', function() {
        game.play();
        return expect(game.isPaused()).toBeFalsy();
      });
    });
    return describe('when started', function() {
      beforeEach(function() {
        return game.play();
      });
      return it('can be paused', function() {
        game.pause();
        return expect(game.isPaused()).toBeTruthy();
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=gameSpec.map
*/
