// Generated by CoffeeScript 1.6.2
(function() {
  describe('The game engine', function() {
    var engine;

    engine = game.engine;
    beforeEach(function() {
      game.load();
      return engine.init();
    });
    it('should have a surface', function() {
      return expect(engine.surface).toBeDefined();
    });
    it('can be initialized', function() {
      return expect(engine.init).toBeDefined();
    });
    it('has a HUD', function() {
      return expect(engine.hud).toBeDefined();
    });
    it('should be paused by default', function() {
      return expect(engine.isPaused()).toBeTruthy();
    });
    it('can be updated', function() {
      return expect(typeof engine.update).toBe('function');
    });
    describe('when paused', function() {
      beforeEach(function() {
        return engine.pause();
      });
      return it('can be resumed', function() {
        engine.play();
        return expect(engine.isPaused()).toBeFalsy();
      });
    });
    return describe('when started', function() {
      beforeEach(function() {
        return engine.play();
      });
      return it('can be paused', function() {
        engine.pause();
        return expect(engine.isPaused()).toBeTruthy();
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=gameSpec.map
*/
