// Generated by CoffeeScript 1.6.2
(function() {
  describe('The game surface', function() {
    var contextMock, surface;

    surface = null;
    contextMock = null;
    beforeEach(function() {
      game.load();
      game.engine.init();
      surface = game.engine.surface;
      return contextMock = createMockFor(CanvasRenderingContext2D);
    });
    it('should be 800 x 600', function() {
      expect(surface.width).toBe(800);
      return expect(surface.height).toBe(600);
    });
    it('can drawLine lines', function() {
      surface.drawLine(10, 20, 30, 40);
      expect(contextMock.moveTo).toHaveBeenCalledWith(10.5, 20.5);
      expect(contextMock.lineTo).toHaveBeenCalledWith(30.5, 40.5);
      return expect(contextMock.stroke).toHaveBeenCalled();
    });
    it('can be drawn', function() {
      return expect(typeof surface.draw).toBe('function');
    });
    return describe('when drawing', function() {
      beforeEach(function() {
        spyOn(game.engine.hud, 'draw');
        return surface.draw();
      });
      it('should clear the screen', function() {
        return expect(contextMock.clearRect).toHaveBeenCalledWith(0, 0, 1001, 601);
      });
      return it('should draw the HUD', function() {
        return expect(game.engine.hud.draw).toHaveBeenCalled();
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=gameSurfaceSpec.map
*/
