// Generated by CoffeeScript 1.6.2
(function() {
  describe('The HUD', function() {
    var hud;

    hud = null;
    beforeEach(function() {
      return hud = game.hud;
    });
    it('can be drawn', function() {
      return expect(typeof hud.draw).toBe('function');
    });
    return describe('when the game is paused', function() {
      var contextMock;

      contextMock = null;
      beforeEach(function() {
        game.pause();
        return contextMock = createMockFor(CanvasRenderingContext2D);
      });
      return it('should display "Game paused"', function() {
        hud.draw();
        expect(contextMock.fillText).toHaveBeenCalledWith('Game paused', 500.5, 280);
        return expect(contextMock.fillText).toHaveBeenCalledWith('Resume...', 500.5, 340);
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=hudSpec.map
*/
