// Generated by CoffeeScript 1.6.2
(function() {
  describe('Upon initialization', function() {
    beforeEach(function() {
      spyOn(window, 'setInterval');
      return game.init();
    });
    return it('should draw the surface 60 times / s', function() {
      return expect(window.setInterval).toHaveBeenCalledWith(game.surface.draw, 1000 / 60);
    });
  });

}).call(this);

/*
//@ sourceMappingURL=initSpec.map
*/
