// Generated by CoffeeScript 1.6.2
(function() {
  describe('The main window', function() {
    it('should have one canvas', function() {
      var canvas;

      canvas = document.getElementsByTagName('canvas');
      return expect(canvas.length).toEqual(1);
    });
    return it('should have a game', function() {
      return expect(game).toBeDefined();
    });
  });

}).call(this);

/*
//@ sourceMappingURL=windowSpec.map
*/
