// Generated by CoffeeScript 1.6.2
(function() {
  var ImageHelper,
    __slice = [].slice;

  window.getCanvas = function() {
    return document.getElementsByTagName('canvas')[0];
  };

  CanvasRenderingContext2D.prototype.drawImage = function() {
    var args;

    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  };

  window.requestAnimationFrame = window.webkitRequestAnimationFrame = function() {};

  window.console.log = function() {};

  ImageHelper = (function() {
    function ImageHelper() {
      ImageHelper.items.push(this);
    }

    ImageHelper.items = [];

    ImageHelper.prototype.onload = function() {};

    ImageHelper.loadAll = function() {
      var item, _i, _len, _ref, _results;

      _ref = ImageHelper.items;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        _results.push(item.onload());
      }
      return _results;
    };

    return ImageHelper;

  })();

  window.Image = ImageHelper;

  require(['game'], function(game) {
    return game.images['space.jpg'] = {
      width: 4000,
      height: 3000
    };
  });

}).call(this);

/*
//@ sourceMappingURL=canvasHelper.map
*/
