// Generated by CoffeeScript 1.6.2
(function() {
  window.getCanvas = function() {
    return document.getElementsByTagName('canvas')[0];
  };

}).call(this);

/*
//@ sourceMappingURL=canvasHelper.map
*/
