// Generated by CoffeeScript 1.6.1
(function() {

  window.canvas = getCanvas();

  window.moveMouseTo = function(x, y) {
    return canvas.onmousemove({
      offsetX: x,
      offsetY: y
    });
  };

  window.mouseUpAt = function(x, y) {
    return canvas.onmouseup({
      offsetX: x,
      offsetY: y
    });
  };

  window.mouseDownAt = function(x, y) {
    return canvas.onmousedown({
      offsetX: x,
      offsetY: y
    });
  };

  window.pressKey = function(keyCode) {
    return document.onkeydown({
      keyCode: keyCode
    });
  };

}).call(this);
