// Generated by CoffeeScript 1.6.2
(function() {
  var canvas;

  canvas = getCanvas();

  window.moveMouseTo = function(x, y) {
    return canvas.onmousemove({
      offsetX: x,
      offsetY: y
    });
  };

  window.mouseUpAt = function(x, y) {
    return canvas.onmouseup({
      offsetX: x,
      offsetY: y
    });
  };

  window.mouseDownAt = function(x, y) {
    return canvas.onmousedown({
      offsetX: x,
      offsetY: y
    });
  };

}).call(this);

/*
//@ sourceMappingURL=mouseHelper.map
*/
